### ISSUE TITLE
GrassError: Error running: `r.cell.area --interface-description`

### ISSUE THREAD

**Issue by BMOJA** [UMN-Hydro/GSFLOW-GRASS#17]
Hi, while building my domain I keep getting an error whith  r.cell.area. I've tested the module r.cell.area standalone and it works perfectly
I'm currently on  
GrassGIS 7.6.14 
python 2.7.14
gsflow 1.2.2

C:\Users\lenovo>python C:\Users\lenovo\Desktop\Essai2\GSFLOW-GRASS-master\domain_builder\buildDomainGRASS.py C:\Users\lenovo\Desktop\Essai2\GSFLOW-GRASS-Cannon-River-Example-master\Cannon.ini
Using specified input file: C:\Users\lenovo\Desktop\Essai2\GSFLOW-GRASS-Cannon-River-Example-master\Cannon.ini
Importing DEM and generating hydrologic correction
ATTENTION: Raster map <DEM_original_import> already exists and will be
           overwritten
Importing raster map <DEM_original_import>...
 100%
OSError error(None): None
Traceback (most recent call last):
  File "C:\Users\lenovo\Desktop\Essai2\GSFLOW-GRASS-master\domain_builder\buildDomainGRASS.py", line 89, in <module>
    r.cell_area(output=cellArea_meters2, units='m2', overwrite=True)
  File "C:\Program Files\GRASS GIS 7.6\etc\python\grass\pygrass\modules\shortcuts.py", line 59, in __getattr__
    name.strip('_').replace('_', '.')))
  File "C:\Program Files\GRASS GIS 7.6\etc\python\grass\pygrass\modules\interface\module.py", line 530, in __init__
    raise GrassError(str_err % self.name)
grass.exceptions.GrassError: Error running: `r.cell.area --interface-description`.

C:\Users\lenovo>

**Comment by awickert** [comment]
Thanks for letting us know! The error is occurring on line 59 of https://github.com/OSGeo/grass-addons/blob/master/grass7/raster/r.cell.area/r.cell.area.py

So it seems that there is some problem with `g.proj`. Could you check if that works on your system?

**Comment by BMOJA** [comment]
Thank you for your fast reply. I just tested g.proj standalone and it worked i even changed my grassgis version and i had the same error.

**Comment by awickert** [comment]
That is very strange. Could you confirm that you are using https://github.com/UMN-Hydro/GSFLOW-GRASS-Cannon-River-Example exactly as it is in that folder? I will try to reproduce the error on my computer.

**Comment by kpretz** [comment]
I'm running into the same problem with my own environment, with my own dataset and the Cannon River Example above. Same environment as the Author, Windows, gsflow 1.2.2, Grass 7.6.1. Was there a resolution? For various reasons it's not easy for me to use Linux. 

Based on the release notes of Grass 7.8.5 it seems as though there's a Windows extension error in Grass which is fixed with the latest release. https://github.com/OSGeo/grass/pull/1143
I tried using 7.8.5 with GSFLOW-GRASS but it uses Python 3 and so not compatible.

**Comment by BMOJA** [comment]
Sadly I couldn't pin down the exact cause of the problem but I suspect it has something to do with the updated python libraries. So to reproduce the cannon river example I switched to Linux. However I dropped the grass-gsflow tool half way through (though it is good) because  it didn't quite respond to my modeling goals instead I used Arcpy-gsflow tools in combination with modelmuse and the results were outstanding.

**Comment by kpretz** [comment]
Figured out a few things in some deep diving. 
- errror occurs when extensions called that are installed to the scripts folder in Grass as .py (don't have this problem with .exe extensions in bin folder)
- problem is in pygrass code. I made some (very hacky) modifications to modules.py to get it to run, also needed to add Grass scripts folder to windows environment path

So I have a working solution for the BuildDomain step, still TBD on whether this will break Grass in other ways.

**Comment by awickert** [comment]
@BMOJA: Agreed that it is related to the Python3 upgrade.

@kpretz: Awesome! Could you make a PR and/or point me to your hacky mods / repo? (I'm looking at https://github.com/kpretz/GSFLOW-GRASS just now -- is that up to date with your local machine?)

I have been planning on trying to get this hunk of code up and running again once I go on sabbatical, and/or tossing it to an interested grad student :) But if you think you have it, YAY and I'd love to incorporate your edits here!

**Comment by kpretz** [comment]
I made the modification to my fork in the grass_modifications folder. I replaced the module.py file in the Grass 7.6 install. Changes are around line 527. Also had to add C:\Users\*user\AppData\Roaming\GRASS7\addons\scripts to path. This had the undesirable side effect of opening each of the extensions python scripts when each one was called. Looks like it's something pretty weird with Grass GIS 7.6 and popen, for some reason it doesn't look for or open python scripts appropriately, but the .exe extensions others made work just fine. I think if you upgrade to Python 3 and Grass 7.8 it will likely be fixed. Release notes in Grass 7.8 suggest they made some fairly major changes to the Popen structure. 

I eventually moved on to something else - Ended up with some errors opening DEMs later on in the domain builder. Didn't file as it might be a result of my hack.

**Comment by awickert** [comment]
Thanks for the notes and work! The combined update to GRASS and update to Python did something bad, and I likely won't be able to get to it until the pandemic semester part 2/3 ends. I'll pull in your changes so I can work with them once that happens.
